version: '3.8'

services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: pdf_backend_prod
    restart: unless-stopped
    volumes:
      - ./data/storage:/app/storage
    env_file:
      - ./config/environments/.env.production
      - ./config/environments/.env.backend
    networks:
      - app-network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: pdf_frontend_prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    env_file:
      - ./config/environments/.env.production
      - ./config/environments/.env.frontend
    networks:
      - app-network
    depends_on:
      - backend

  certbot:
    image: certbot/certbot
    container_name: pdf_certbot_prod
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge
