# PDF Learning Platform - Development Docker Compose
version: '3.8'

services:
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    container_name: pdf_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data/storage:/app/storage
      - ./ssl/certificates:/etc/ssl:ro
    environment:
      - ENVIRONMENT=development
      - PDF_STORAGE_PATH=/app/storage/pdfs
      - DATABASE_URL=sqlite+aiosqlite:///./storage/database.db
    env_file:
      - config/environments/development.env
    depends_on:
      - frontend
    networks:
      - pdf_network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    container_name: pdf_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    networks:
      - pdf_network

networks:
  pdf_network:
    driver: bridge

volumes:
  node_modules: